"""add new colm in address

Revision ID: 76142fa1ebb0
Revises: fd25e40a22f8
Create Date: 2025-05-09 17:01:50.253947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76142fa1ebb0'
down_revision: Union[str, None] = 'fd25e40a22f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('pincode', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'pincode')
    # ### end Alembic commands ###
